INSERT INTO USER (USER_ID, USERNAME, PASSWORD) VALUES (1,'Ed', '$2a$10$whyJR3YJjDL4BEg2KdjeEuKtBV5KM7XZwZ1UtF.p5.M/t81rvRKwi');
INSERT INTO USER (USER_ID, USERNAME, PASSWORD) VALUES (2,'Dev', '$2a$10$whyJR3YJjDL4BEg2KdjeEuKtBV5KM7XZwZ1UtF.p5.M/t81rvRKwi');

INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (1,'Ed', 'ROLE_USER');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (2,'Dev', 'ROLE_ADMIN');
