INSERT INTO USER (USER_ID, USERNAME, PASSWORD) VALUES (1,'Ed', 'password');
INSERT INTO USER (USER_ID, USERNAME, PASSWORD) VALUES (2,'Dev', 'password');

INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (1,'Ed', 'ROLE_USER');
INSERT INTO AUTH_USER_GROUP (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP) VALUES (2,'Dev', 'ROLE_ADMIN');
